FROM python:3

RUN mkdir /app
COPY requirements.txt /app
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt
ONBUILD RUN pip install -r /app/requirements.txt
ONBUILD COPY README.md /app/
